apiVersion: apps/v1
kind: Deployment
metadata:
  name: olympsis-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olympsis-chat
  template:
    metadata:
      labels:
        app: olympsis-chat
    spec:
      containers:
      - name: olympsis-chat
        imagePullPolicy: Always
        image: us.gcr.io/diesel-nova-366902/chat-service:v0.1
        ports:
        - containerPort: 7011
        readinessProbe:
          httpGet:
            path: /healthz
            port: 7011
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7011
          initialDelaySeconds: 30
          periodSeconds: 60